name: ffhq
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=1.3.0
  - astroid=2.3.3
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.8
  - freetype=2.9.1
  - idna=2.8
  - intel-openmp=2020.0
  - isort=4.3.21
  - jpeg=9b
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - mccabe=0.6.1
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - mypy=0.750
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1d
  - pillow=7.0.0
  - pip=20.0.2
  - psutil=5.6.7
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pylint=2.4.4
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.8.1
  - readline=7.0
  - requests=2.22.0
  - scipy=1.4.1
  - setuptools=45.2.0
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.1
  - urllib3=1.25.8
  - wheel=0.34.2
  - wrapt=1.11.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7

